export const BASE_URL = "https://gab.com";

export const COMMENTS = [
  "Great article! 👍",
  "Interesting read. 😊",
  "Well said. 👏",
  "Nice insights. ❤️",
  "Awesome content. 👌",
  "Keep it up! 😄",
  "Very informative. 📚",
  "Love it! 💖",
  "Thumbs up! 👍",
  "Bravo! 👏",
  "Impressive work! 👍",
  "Exactly! 😃",
  "I'm blown away. 😲",
  "Absolutely agree! 👍",
  "Kudos! 👏",
  "Spot on! 👌",
  "Overrated. 😐",
  "It's mediocre. 😕",
  "Informative, thanks. 📖",
  "Impressed! 👍",
  "Well done. 👏",
  "A masterpiece! 🎨",
  "So insightful. 😊",
  "Outstanding! 👍",
  "Brilliant! 👏",
  "I'm in awe. 😲",
  "I'm loving it! ❤️",
  "Well expressed. 👌",
  "Deserves an award. 🏆",
  "I've seen better. 😐",
  "Very insightful. 😊",
  "I'm inspired! 😃",
  "Outstanding work! 👍",
  "Well put. 👏",
  "Fascinating! 😊",
  "Exceptional! 👌",
  "I'm thrilled! 😃",
  "Impressive analysis! 👍",
  "Nailed it! 👏",
  "I'm impressed! 😊",
  "Brilliantly stated. 👌",
  "Magnificent! 👏",
  "I agree wholeheartedly! 👍",
  "Exemplary! 👏",
  "Gold star! 🌟",
  "Exceptionally good! 👌",
  "Incredible! 😃",
  "Perfect! 👏",
  "So-so. 😐",
  "Well worth the read! 👌",
  "This deserves recognition. 👏",
  "A bit underwhelming. 😕",
  "This is a gem! 💎",
  "I'm neutral on this. 😐",
  "Quite impressive! 👍",
  "Not my cup of tea. 😕",
  "Engaging article! 👏",
  "A mixed bag. 😐",
  "Thumbs down. 👎",
  "Highly recommended! 👌",
  "Meh, it's alright. 😐",
  "Very well written! 👏",
  "Could be improved. 😕",
  "Well done, author! 👌",
  "I have reservations. 😐",
  "Impressively done! 👍",
  "Not quite there yet. 😕",
  "Excellent job! 👏",
  "A little disappointing. 😕",
  "A must-read! 👌",
  "I'm on the fence. 😐",
  "Enlightening! 😊",
  "It has potential. 👍",
  "Well thought out! 👌",
  "Needs more substance. 😕",
  "I'm loving this! ❤️",
  "Uninspiring at best. 😐",
  "Impressive points! 👌",
  "Somewhat lacking. 😕",
  "I'm enthusiastic! 😃",
  "Lacking depth. 😐",
  "I applaud this effort! 👏",
  "Promising but shallow. 😐",
  "Incredible insights! 😊",
  "Needs further refinement. 😕",
  "It's a winner! 🏆",
  "Lacks depth and breadth. 😐",
  "I'm sold on this! 👍",
  "Room for improvement. 😕",
  "I'm captivated! 😊",
  "Loses focus at times. 😕",
  "Bravo, author! 👏",
  "Shows potential. 👍",
  "Top-notch writing! 👌",
  "Not quite convincing. 😕",
  "Well-articulated! 👏",
  "Mixed feelings. 😐",
  "A valuable contribution! 👌",
  "It's a bit fuzzy. 😕",
  "Impressive arguments! 👌",
  "Somewhat hard to follow. 😐",
  "I'm thoroughly impressed! 👍",
  "Misses the mark. 😕",
  "Incredibly enlightening! 😊",
  "A bit lengthy for me. 😐",
  "Superbly crafted! 👏",
  "Doesn't quite hit home. 😕",
  "Absolutely stunning! 👌",
  "Well above average. 👍",
  "I couldn't agree more! 👏",
  "It's a work in progress. 😕",
  "I'm hooked on this! 😃",
  "Needs some polishing. 😕",
  "Intriguing insights! 👌",
  "Needs better structure. 😕",
  "I'm completely hooked! 😃",
  "Leaves me wanting more. 👏",
  "Incredibly informative! 👍",
  "A little hard to digest. 😐",
  "Outstanding achievement! 👌",
  "Well worth the time! 👏",
  "I'm a little skeptical. 😕",
  "Simply amazing! 👍",
  "Leaves much to be desired. 😕",
  "I'm deeply impressed! 👏",
  "Intriguing but unclear. 😕",
  "Bravo, well done! 👏",
  "Lacks coherence. 😐",
  "A truly great read! 👏",
  "Almost hits the mark. 😊",
  "Exceptional writing! 👌",
  "Somewhat convoluted. 😕",
  "I'm thoroughly entertained! 😃",
  "Leaves room for doubt. 😐",
];
